#!/usr/bin/env node
/**
 * @file .glimpse/hooks/install.mjs
 * @description Install git hooks for structured routines
 */

import { writeFileSync, existsSync, mkdirSync, chmodSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');
const GIT_HOOKS_DIR = path.join(ROOT, '.git', 'hooks');

// Ensure .git/hooks exists
if (!existsSync(GIT_HOOKS_DIR)) {
  console.error('No .git directory found. Are you in a git repository?');
  process.exit(1);
}

// Create pre-commit hook
const preCommitHook = `#!/bin/bash
# Auto-generated by glimpse-agentic hook installer
# Triggers structured routine before commits

echo "🪝 Running Glimpse pre-commit hook..."

node .glimpse/hooks/pre-process.mjs

exit $?  # Pass through exit code
`;

// Create pre-push hook
const prePushHook = `#!/bin/bash
# Auto-generated by glimpse-agentic hook installer
# Triggers strict validation before push

echo "🪝 Running Glimpse pre-push hook..."

node scripts/ci-check.mjs --strict

exit $?
`;

// Install hooks
const hooks = [
  { name: 'pre-commit', content: preCommitHook },
  { name: 'pre-push', content: prePushHook }
];

for (const hook of hooks) {
  const hookPath = path.join(GIT_HOOKS_DIR, hook.name);
  
  if (existsSync(hookPath)) {
    console.log(`⚠️  ${hook.name} already exists, backing up to ${hook.name}.backup`);
    writeFileSync(`${hookPath}.backup`, require('node:fs').readFileSync(hookPath));
  }
  
  writeFileSync(hookPath, hook.content);
  chmodSync(hookPath, 0o755); // Make executable
  
  console.log(`✅ Installed ${hook.name}`);
}

console.log('\n📋 Hooks installed successfully!');
console.log('   - pre-commit: Runs structured routine before commits');
console.log('   - pre-push: Runs strict CI check before pushes');
console.log('\nTo uninstall: restore .git/hooks/*.backup files');
