import type { EligibilityAttribute } from "./types.js";

export const DEFAULT_ATTRIBUTE_CATALOG: readonly EligibilityAttribute[] = [
  {
    id: "provenance-traceability",
    label: "Provenance traceability",
    dimension: "governance",
    polarity: "positive",
    propertyKeys: ["provenance", "auditability"],
    baseBand: [0.62, 0.84],
    argMultipliers: { governance: 0.34, observability: 0.16 },
    observationHooks: ["show provenance in summaries", "keep credit labels visible"],
    conditionHooks: ["flag when provenance drops below watch threshold"],
    tableColumns: ["weightRaw", "weightBand", "conditionIds", "creditLabel"],
  },
  {
    id: "fail-closed-clarity",
    label: "Fail-closed clarity",
    dimension: "governance",
    polarity: "positive",
    propertyKeys: ["clarity", "ambiguity_handling"],
    baseBand: [0.54, 0.76],
    argMultipliers: { governance: 0.28, usability: 0.08 },
    observationHooks: ["name the failure boundary", "show who can override"],
    conditionHooks: ["emit priority note if clarity remains weak under governance bias"],
    tableColumns: ["weightRaw", "weightBand", "dimensionScore"],
  },
  {
    id: "operator-clarity",
    label: "Operator clarity",
    dimension: "usability",
    polarity: "positive",
    propertyKeys: ["clarity", "operator_empathy"],
    baseBand: [0.57, 0.8],
    argMultipliers: { usability: 0.32, observability: 0.08 },
    observationHooks: ["prefer short labels", "surface action and consequence together"],
    conditionHooks: ["note when governance wins but operator clarity lags"],
    tableColumns: ["weightRaw", "weightBand", "observationIds"],
  },
  {
    id: "entry-friction",
    label: "Entry friction",
    dimension: "usability",
    polarity: "negative",
    propertyKeys: ["friction"],
    baseBand: [0.24, 0.48],
    argMultipliers: { usability: 0.24, integration: 0.08 },
    observationHooks: ["annotate where the entry path feels heavy"],
    conditionHooks: ["flag when friction rises while usability is emphasized"],
    tableColumns: ["weightRaw", "weightBand", "hierarchyRank"],
  },
  {
    id: "tool-call-fit",
    label: "Tool-call fit",
    dimension: "integration",
    polarity: "positive",
    propertyKeys: ["tooling_fit", "adapter_readiness"],
    baseBand: [0.5, 0.76],
    argMultipliers: { integration: 0.3, operational_fit: 0.1 },
    observationHooks: ["show which tool surfaces are natural fits"],
    conditionHooks: ["flag when candidate shape is good but tool-call fit is low"],
    tableColumns: ["weightRaw", "weightBand", "creditLabel"],
  },
  {
    id: "vertical-coverage",
    label: "Vertical coverage",
    dimension: "integration",
    polarity: "positive",
    propertyKeys: ["entry_flexibility", "tooling_fit"],
    baseBand: [0.46, 0.72],
    argMultipliers: { integration: 0.22, usability: 0.06 },
    observationHooks: ["describe where the routine can expand later"],
    conditionHooks: ["flag narrow vertical coverage under integration-heavy args"],
    tableColumns: ["dimensionScore", "hierarchyRank"],
  },
  {
    id: "credit-visibility",
    label: "Credit visibility",
    dimension: "observability",
    polarity: "positive",
    propertyKeys: ["auditability", "table_fitness"],
    baseBand: [0.56, 0.82],
    argMultipliers: { observability: 0.34, governance: 0.12 },
    observationHooks: ["credit every row to its source pass and artifact"],
    conditionHooks: ["watch if credits disappear from collection output"],
    tableColumns: ["sourcePass", "sourceArtifact", "creditLabel"],
  },
  {
    id: "formula-readiness",
    label: "Formula readiness",
    dimension: "observability",
    polarity: "positive",
    propertyKeys: ["table_fitness", "clarity"],
    baseBand: [0.52, 0.82],
    argMultipliers: { observability: 0.24, usability: 0.1 },
    observationHooks: ["keep row/column output formula-friendly"],
    conditionHooks: ["flag when row output is rich but formula ready score stays low"],
    tableColumns: ["weightRaw", "weightBand", "dimensionScore"],
  },
  {
    id: "exclusive-boundary",
    label: "Exclusive boundary strength",
    dimension: "operational_fit",
    polarity: "positive",
    propertyKeys: ["isolation", "provenance"],
    baseBand: [0.58, 0.84],
    argMultipliers: { operational_fit: 0.32, governance: 0.08 },
    observationHooks: ["keep responsibility exclusive, not alignment-specific"],
    conditionHooks: ["flag when isolation weakens under broader form targets"],
    tableColumns: ["weightRaw", "weightBand", "creditLabel"],
  },
  {
    id: "runtime-parameter-shape",
    label: "Runtime parameter shape",
    dimension: "operational_fit",
    polarity: "positive",
    propertyKeys: ["entry_flexibility", "adapter_readiness"],
    baseBand: [0.48, 0.74],
    argMultipliers: { operational_fit: 0.24, integration: 0.12 },
    observationHooks: ["keep argv surfaces stable and pointed"],
    conditionHooks: ["flag when args become broad enough to blur the boundary"],
    tableColumns: ["sourcePass", "argvSignature", "dimensionScore"],
  },
] as const;

export function getDefaultAttributeCatalog(): EligibilityAttribute[] {
  return DEFAULT_ATTRIBUTE_CATALOG.map((attribute) => ({
    ...attribute,
    propertyKeys: [...attribute.propertyKeys],
    observationHooks: [...attribute.observationHooks],
    conditionHooks: [...attribute.conditionHooks],
    tableColumns: [...attribute.tableColumns],
    argMultipliers: { ...attribute.argMultipliers },
    baseBand: [attribute.baseBand[0], attribute.baseBand[1]],
  }));
}
