export type {
  AnalogWeight,
  BeatRailEntry,
  CollectionRow,
  CollectionTable,
  CompileTarget,
  ConditionNote,
  StrugglePoint,
  ConditionSeverity,
  CycleBeat,
  CycleSignal,
  CycleSignalKind,
  CycleSnapshot,
  CycleSnapshotPoint,
  CycleStatus,
  CycleTimelineEntry,
  EligibilityAttribute,
  EligibilityCandidate,
  EligibilityProperty,
  EligibilityState,
  EligibilityValidationResult,
  EndpointSpec,
  EndpointStatus,
  EvolutionCase,
  EvolutionCaseSummary,
  FormArtifact,
  HandoffRecord,
  HandoffStatus,
  HierarchySlice,
  IntegrationDimension,
  MomentumFrame,
  ObservationNote,
  PromotionGateDecision,
  PromotionGateResult,
  ProvenanceCredit,
  ReturnRecord,
  RoutineArgs,
  RoutineResult,
  SafeRoutineEvaluation,
  TableScope,
  WeightBand,
} from "./types.js";

export { DEFAULT_ATTRIBUTE_CATALOG, getDefaultAttributeCatalog } from "./catalog.js";
export { DEFAULT_EXECUTE_SCENARIO, EligibilityRouter } from "./demo-pipeline.js";
export {
  DEFAULT_SIGNAL_WEIGHTS,
  EvolutionCycleStore,
  advanceCycle,
  evaluatePromotionGate,
  getCycleSnapshot,
  getEvolutionCycleStore,
  hydrateExistingCases,
  listActiveCycles,
  openEvolutionCase,
  recordCycleSignal,
  recordHandoff,
  upsertEndpointSpec,
} from "./evolution.js";
export { FIXTURE_CANDIDATES, getFixtureCandidateById, getFixtureCandidates } from "./examples.js";
export { compileFormArtifacts } from "./forms.js";
export {
  ROUTINE_PIPELINE_ID,
  buildArgvSignature,
  buildDeterministicTimestamp,
  buildRoutinePipeline,
  evaluateRoutine,
  explainHierarchy,
  latestDeposit,
  normalizeRoutineArgs,
  resolveCandidates,
  safeEvaluateRoutine,
  validateCandidates,
} from "./pipeline.js";
export {
  advanceCycleHandler,
  buildServer,
  collectTableHandler,
  compileFormsHandler,
  evaluateCandidateHandler,
  evaluatePromotionGateHandler,
  explainHierarchyHandler,
  getCycleSnapshotHandler,
  listActiveCyclesHandler,
  listAttributeCatalogHandler,
  openEvolutionCaseHandler,
  recordCycleSignalHandler,
  recordHandoffHandler,
  startServer,
  upsertEndpointSpecHandler,
} from "./server.js";
export { buildCollectionTable } from "./table.js";
export {
  emitEligibilityAudit,
  withAudit,
  emitCaseOpenedSignal,
  emitSignalRecordedSignal,
  emitHandoffRecordedSignal,
  emitEndpointUpsertedSignal,
  emitBeatAdvancedSignal,
  emitPromotionGateEvaluatedSignal,
} from "./routing.js";
export type { EligibilityAuditMetadata } from "./routing.js";
export { checkTheLine, holdTheLine } from "./line-audit.js";
export type { LineFinding, LineAuditResult } from "./line-audit.js";
export {
  onEvolutionCaseOpened,
  onCycleSignalRecorded,
  onPromotionGateEvaluated,
  onCaseStatusChanged,
  initializeHooks,
} from "./hooks.js";
export {
  weightBandToOpacity,
  cycleStatusToState,
  gateDecisionToCool,
  moodToToken,
  timestampToRecency,
  endpointStatusToConsent,
  conditionSeverityToOpacity,
  momentumDriftToState,
  resolveCoolStep,
  resolveTraceOpacity,
  resolveMemoryRecency,
  LAYER_LABELS,
  ATTENTION_HEADS,
  theta,
  radius,
  angularDistance,
  pythagoreanDistance,
  sortByAngle,
  clusterByRadius,
  arcsPerLayer,
  attentionScore,
  attend,
} from "./token-bridge.js";
export {
  MAX_METADATA_KEYS,
  MAX_METADATA_VALUE_LENGTH,
  sanitizeAuditMetadata,
  sanitizeLogValue,
} from "./sanitize.js";
