/**
 * Threat coverage confirmations — persisted harness run→threat links.
 *
 * When harness-server completes a scenario run, it appends a ConfirmationEntry
 * to this store. The heatmap builder reads the store to overlay `confirmedVia`
 * on (threatId, projectId) cells.
 *
 * File: ${ORI_DATA_DIR}/confirmations/heatmap-confirmations.ndjson
 */

import { promises as fs } from "fs";
import path from "path";
import { getConfig } from "./config.js";

const config = getConfig();

function confirmationsPath(): string {
  return path.join(config.dataDir, "confirmations", "heatmap-confirmations.ndjson");
}

export interface ConfirmationEntry {
  /** Unique ID for this confirmation event (generated by harness-server). */
  harnessRunId: string;
  /** Scenario that produced the run. */
  scenarioId: string;
  scenarioName: string;
  /** Threat IDs confirmed by this run (from HarnessScenario.threatIds). */
  threatIds: string[];
  /** Project registry ID this run tests against (optional — defaults to GRID-main). */
  projectId?: string;
  /** ISO timestamp of run completion. */
  confirmedAt: string;
}

/**
 * Append a confirmation entry after a successful harness run.
 * Called by harness-server/src/runner.ts (direct filesystem write — no MCP hop).
 */
export async function appendConfirmation(entry: ConfirmationEntry): Promise<void> {
  const file = confirmationsPath();
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.appendFile(file, JSON.stringify(entry) + "\n", "utf-8");
}

/**
 * Load all stored confirmation entries, most recent first.
 */
export async function loadConfirmations(): Promise<ConfirmationEntry[]> {
  try {
    const raw = await fs.readFile(confirmationsPath(), "utf-8");
    const entries = raw
      .trim()
      .split("\n")
      .filter(Boolean)
      .map((line) => {
        try {
          return JSON.parse(line) as ConfirmationEntry;
        } catch {
          return null;
        }
      })
      .filter((e): e is ConfirmationEntry => e !== null);
    // Most recent first
    entries.sort((a, b) => b.confirmedAt.localeCompare(a.confirmedAt));
    return entries;
  } catch {
    return [];
  }
}

/**
 * Build a lookup map: `"threatId:projectId"` → most-recent harnessRunId.
 * Used by the heatmap builder to overlay confirmedVia on cells.
 */
export async function buildConfirmationMap(): Promise<Map<string, string>> {
  const entries = await loadConfirmations();
  const map = new Map<string, string>();
  // Entries are already most-recent first; only write each key once.
  for (const entry of entries) {
    for (const threatId of entry.threatIds) {
      const key = `${threatId}:${entry.projectId ?? ""}`;
      if (!map.has(key)) {
        map.set(key, entry.harnessRunId);
      }
    }
  }
  return map;
}
